      - name: Verify Deployment & Print URL
        run: |
          SITE_URL="https://libin-static-site-demo.s3.amazonaws.com/index.html"
          echo "Checking site status..."
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $SITE_URL)
          echo "HTTP Status Code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Deployment check failed!"
            exit 1
          else
            echo "✅ Deployment successful! Site is live: $SITE_URL"
          fi
